apiVersion: v1
kind: Pod
metadata:
  name: promk8s-demo
  labels:
    A: B
  annotations:
    C: D
spec:
  containers:
  - name: promk8sjob
    image: promk8s:current
    ports:
      - containerPort: 8000
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
      - path: "uid"
        fieldRef:
          fieldPath: metadata.uid
