version: "3"
services:
  database:
    image: "mongo"
    container_name: "mongo-db-container"
    environment:
      - MONGO_INITDB_DATABASE=lightstep
      - MONGO_INITDB_ROOT_USERNAME=lightstep
      - MONGO_INITDB_ROOT_PASSWORD=lightstep
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
  redis:
    image: "redis"
    container_name: "redis-container"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis-volume:/data
      - ./db/redis.conf:/usr/local/etc/redis/redis.conf
