version: "3"
services:
  nodered:
    image: nodered/node-red:latest-12
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered:/data:rw
    networks:
      - lightstep
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=lightstep
      - INFLUXDB_USER=lightstep
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb:rw
    networks:
      - lightstep
  grafana:
    image: grafana/grafana:7.3.0
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - lightstep

networks:
  lightstep:
